//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLHProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDossierAdmission
    {
        public int IDAdmission { get; set; }
        public Nullable<bool> chirurgieProgrammee { get; set; }
        public Nullable<System.DateTime> dateAdmission { get; set; }
        public Nullable<System.DateTime> dateChirurgie { get; set; }
        public Nullable<System.DateTime> dateConge { get; set; }
        public Nullable<bool> televiseur { get; set; }
        public Nullable<bool> telephone { get; set; }
        public string NSS { get; set; }
        public Nullable<int> numeroLit { get; set; }
        public Nullable<int> IDMedecin { get; set; }
    
        public virtual tblLit tblLit { get; set; }
        public virtual tblMedecin tblMedecin { get; set; }
        public virtual tblPatient tblPatient { get; set; }
    }
}
