//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLHProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLit()
        {
            this.tblDossierAdmissions = new HashSet<tblDossierAdmission>();
        }
    
        public int numerolit { get; set; }
        public Nullable<bool> occupe { get; set; }
        public Nullable<int> numeroType { get; set; }
        public Nullable<int> IDDepartement { get; set; }
    
        public virtual tblDepartement tblDepartement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDossierAdmission> tblDossierAdmissions { get; set; }
        public virtual tblTypesLit tblTypesLit { get; set; }
    }
}
